version: '3.4'

services:
  gh.ngmug.webapi:
    image: ${DOCKER_REGISTRY-}ghngmug
    build:
      context: .
      dockerfile: Gh.Ngmug.WebApi/Dockerfile
    depends_on:
      - db
      - frontend

  db:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
      - "1433:1433"

    environment:    
        SA_PASSWORD: "sql_pw_1234"
        ACCEPT_EULA: "Y"

  frontend:
    image: ngmug:latest
    ports:
      - "8000:80"